services:
  - type: web
    name: metabase
    env:  docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    containerPort: 3000        # 👈 Render ya no escanea
    envVars:
      - key: PORT              # 👈 Render inyecta 3000
        value: "3000"
    healthCheckPath: /api/health
