services:
  - type: web
    env:  docker
    name: metabase
    plan: free
    dockerfilePath: ./Dockerfile
    containerPort: 3000        # ← clave: Render mapea 3000 y NO escanea
    healthCheckPath: /api/health