services:
  - type: web
    env:  docker
    name: metabase
    plan: free
    dockerfilePath: ./Dockerfile
    containerPort: 3000      # Render sabrá que tu contenedor escucha aquí
    healthCheckPath: /api/health

