services:
  - type: web
    env:  docker
    name: metabase
    plan: free
    dockerfilePath: ./Dockerfile
    # Si quieres que Render se base sólo en PORT, omite containerPort.
    healthCheckPath: /api/health
