services:
  - type: web
    name: metabase
    env:  docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    containerPort: 3000          # Render deja de escanear
    envVars:
      - key: PORT                # <-- crítico
        value: "3000"
    healthCheckPath: /api/health